version: '3.8'

services:
  api:
    build: ./
    command: uvicorn main:app --workers 1 --host 0.0.0.0 --port 80 --reload
    volumes:
      - .:/MOTOR
    ports:
      - 80:80
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
